version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: clinic-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: clinic_password_9988
      POSTGRES_DB: clinic_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
    driver: local
